#!/bin/bash

#PBS -l nodes=1:ppn=1
#PBS -l walltime=00:15:00


#parse config.json for input parameters 

t1=$(jq -r .t1 config.json)
computed=$(jq -r .computed config.json)
groud_truth=$(jq -r .groud_truth config.json)


if ! ( [ -z "${t1}" ]  || [  "${t1}" == "null" ] ); then

	echo "t1: "${t1}



	outputdir=${PWD}"/segmentation"
	mkdir -p ${outputdir}
	output=${outputdir}'/segmentation.nii.gz'

	chkcp_dir=${PWD}
	singularity exec -e  --nv docker://gamorosino/bl_app_dbb_disseg python predict.py  $t1 ${output} ${chkcp_dir} 

	cp './data/label.json' ${outputdir}

elif  ! ( [ -z "${computed}" ]  || [  "${computed}" == "null" ] || [ -z "${groud_truth}" ]  || [  "${groud_truth}" == "null" ]   ); then

	echo "computed: "${computed}
	echo "groud_truth: "${groud_truth}


	#outputdir=${PWD}"/segmentation"
	#mkdir -p ${outputdir}
	#output=${outputdir}'/segmentation.nii.gz'

	singularity exec -e  --nv docker://gamorosino/bl_app_dbb_disseg python -m  dice_score.py  ${computed} ${groud_truth} 

	


fi
