#!/bin/bash

#PBS -l nodes=1:ppn=1
#PBS -l walltime=00:05:00


#parse config.json for input parameters 

t1=$(jq -r .t1 config.json)

echo "t1: "${t1}



outputdir=${PWD}"/outputdir"
output=${outputdir}'/segmentation.nii.gz'

chkcp_dir='.'
singularity exec -e gamorosino/bl_app_dbb_disseg:latest python predict.py  $t1 ${output} ${chkcp_dir} 

cp './data/label.json' ${outputdir}




